In [1]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("orginal arrays")
print(a)
print(b)

orginal arrays
[10 20 30 40 50]
[ 2  4  5  8 10]


In [2]:
print("\nvector additions")
print(a+b)


vector additions
[12 24 35 48 60]


In [3]:
print("\nvector subractions")
print(a-b)


vector subractions
[ 8 16 25 32 40]


In [4]:
print("\nvector multiplication")
print(a*b)


vector multiplication
[ 20  80 150 320 500]


In [5]:
print("\nvector division")
print(a/b)


vector division
[5. 5. 6. 5. 5.]


In [6]:
print("\nvector dot product")
print(a.dot(b))


vector dot product
1070


In [7]:
print("\nscalar multiplication")
sclr=5


scalar multiplication


In [8]:
print("\nscalar multiplication")
sclr=5
print("scalar value=",sclr)
print("array=",a)
print("result=",a*sclr)


scalar multiplication
scalar value= 5
array= [10 20 30 40 50]
result= [ 50 100 150 200 250]


In [24]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
print("\n\nnumpy.vectorize method")
print("(Return x-y ifx>y.otherwise return x+y)")
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("array1:",arr1)
print("array2",arr2)
print("result:",vec_func(arr1,arr2))
    



numpy.vectorize method
(Return x-y ifx>y.otherwise return x+y)
array1: [10, 4, 20]
array2 [2, 3, 30]
result: [ 8  1 50]
