In [1]:
import numpy as np
a=np.array([1,2,4],[5,8,7])
print(a)

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [2]:
a = np.array([[1, 2, 4], [5, 8, 7]])

print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [3]:
b = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", b)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
c=np.full((3,3),6)
print("\nAn array initialised with all 6s.\n",c)


An array initialised with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [7]:
d = np.random.random((2, 2))
print ("\nA random array:\n", d)


A random array:
 [[0.46374789 0.18925359]
 [0.60360714 0.55470983]]


In [8]:
e=np.arrange(0,30,5)
print("\n A sequential array with steps of 5:\n",e)

AttributeError: module 'numpy' has no attribute 'arrange'

In [9]:
d = np.random.random((2, 2))
print ("\nA random array:\n", d)


A random array:
 [[0.19387695 0.14322412]
 [0.76461845 0.66925642]]


In [10]:
d = np.random.random((2, 2))
print ("\nA random array:\n", d)


A random array:
 [[0.06131478 0.73736711]
 [0.28461885 0.42159063]]


In [11]:
e = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", e)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [12]:
arr = np.array([[1, 2, 3, 4],[5, 2, 4, 2],[1, 2, 0, 1]])
newarr = arr.reshape(4, 3)
print ("\nOriginal array:\n", arr)
print ("Reshaped array[4,3]:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [13]:
flarr = arr.flatten()
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Fattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [14]:
print("\nNo. of dimensions: ", arr.ndim)


No. of dimensions:  2


In [15]:
print("\nNo. of shape: ", arr.shape)


No. of shape:  (3, 4)


In [16]:
print("\nsize of array: ", arr.size)


size of array:  12


In [17]:
print("\nArray stores elements of type: ",arr.dtype)


Array stores elements of type:  int32


In [18]:
newtype=arr.astype('f')
print("\nConverted array elements:\n",newtype)
print("Converted array type:",newtype.dtype)


Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32


In [5]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2,6,7,8],[3,-7,4,2.0]])
print("orginal array:\n",arr)

orginal array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.   6.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [7]:
print("\n Every other rows : arr[0:3:2]:\n",arr[0:3:2])


 Every other rows : arr[0:3:2]:
 [[-1.  2.  0.  4.]
 [ 2.  6.  7.  8.]]


In [11]:
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\n Elements at indices (0,3),(1,2),(2,1),""(3,0):\n",temp)


 Elements at indices (0,3),(1,2),(2,1),(3,0):
 [4. 6. 6. 3.]


In [12]:
cond=arr>2
temp=arr[cond]
print("\n Elements greater than 2:\n",temp)


 Elements greater than 2:
 [4. 4. 6. 6. 7. 8. 3. 4.]


In [13]:
arr=np.array([1,2,3,4,5,6,7])
print("\n orginal array:,arr")
print("\n Returns every other elements in the array:arr[::2]",arr[::2])


 orginal array:,arr

 Returns every other elements in the array:arr[::2] [1 3 5 7]


In [14]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print("\n orginal arrays:\n",arr1,arr2)
print("\n joined array:\n",arr)


 orginal arrays:
 [1 2 3] [4 5 6]

 joined array:
 [1 2 3 4 5 6]


In [15]:
arr=np.hstack((arr1,arr2))
print("\n vertical joining:\n",arr)


 vertical joining:
 [1 2 3 4 5 6]


In [16]:
arr=np.dstack((arr1,arr2))
print("\n Depth joinin:\n",arr)


 Depth joinin:
 [[[1 4]
  [2 5]
  [3 6]]]


In [17]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print("\n orginal array:\n",arr)
print("\nsplitted array:\n",newarr)


 orginal array:
 [1 2 3 4 5 6]

splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [18]:
print("\nsplitted array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


splitted array in another form:

[1 2]
[3 4]
[5 6]
